### ISSUE TITLE
[connect] Component customization support

### ISSUE THREAD

**Issue by danilo-leal** [mui/mui-design-kits#336]
### Search keywords

connect component support customization

### Latest version

- [X] I have tested the latest version

### Summary

This issue tracks how many components the Connect plugin already supports for component customization.

- [ ] Input
  - [ ] Autocomplete
  - [x] Button & Button Group
  - [ ] Checkbox
  - [ ] Floating Action Button
  - [ ] Radio Group
  - [ ] Rating
  - [ ] Select
  - [ ] Slider
  - [x] Switch
  - [ ] Text Field
  - [ ] Transfer List
  - [ ] Toggle Button
- [ ]  Data Display
  - [ ] Avatar
  - [ ] Badge
  - [ ] Chip
  - [ ] Divider
  - [ ] List
  - [ ] Table
  - [ ] Tooltip
  - [x] Typography
- [ ] Feedback
  - [ ] Alert
  - [ ] Backdrop
  - [ ] Dialog
  - [ ] Progress
  - [ ] Skeleton
  - [ ] Snackbar
- [ ] Surfaces
   - [ ] Accordion
   - [ ] App Bar
   - [ ] Card
   - [ ] Paper
- [ ] Navigation
   - [ ] Bottom Navigation
   - [ ] Breadcrumbs
   - [ ] Drawer
   - [ ] Link
   - [ ] Menu
   - [ ] Pagination
   - [ ] Speed Dial
   - [ ] Stepper
   - [ ] Tabs
- [ ] MUI X
   - [ ] Data Grid
   - [ ] Date & Time Pickers
   - [ ] Charts
   - [ ] Tree View
